export const TASKS_PENDING_REQUEST = "TASKS/PENDING_REQUEST";
export const TASKS_ERROR_REQUEST = "TASKS/GET_ERROR_REQUEST";
export const TASKS_GET_SUCCESS = "TASKS/GET_TASKS_SUCCESS";
export const TASKS_CREATE_SUCCESS = "TASKS/CREATE_SUCCESS";
export const TASKS_UPDATE_SUCCESS = "TASKS/UPDATE_SUCCESS";
